<form action="agregarViaje/<?= $DestinoId ?>" method="GET" class="form-categoria">
    <div>
        <label for="fecha">fecha</label>
        <input class="form-control form-control-sm" name="fecha" type="date" placeholder="Fecha">
        <br>
        <label for="hora">hora</label>
        <input class="form-control form-control-sm" name="hora" type="time" placeholder="Hora">
       
    </div>
    <button type="submit" class="btn btn-secondary">Agregar viajes</button>
    <?php
    if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>
</form>