<form action="agregarViaje/<?= $destinoId ?>" method="POST" class="form-categoria">
    <div>
        <label for="fecha_viaje">fecha</label>
        <input class="form-control form-control-sm" name="fecha_viaje" type="date" placeholder="Fecha">
        <br>
        <label for="hora_viaje">hora</label>
        <input class="form-control form-control-sm" name="hora_viaje" type="time" placeholder="Hora">
       
    </div>
    <button type="submit" class="btn btn-secondary">Agregar viajes</button>
    <?php
    if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>
</form>