<?php require_once './templates/header.phtml';
?>
<form action="actualizarViaje/<?= $idViajes   ?>" method="POST" class="form-categoria">

    <div>
        <label for="nuevaFecha">Fecha</label>
        <input class="form-control form-control-sm" name="nuevaFecha" type="text" placeholder="Fecha">

        <label for="nuevaHora">Hora</label>
        <input class="form-control form-control-sm" name="nuevaHora" type="text" placeholder="Hora">

    </div>
    <?php if (isset($error)) : ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>
    <button type="submit" class="btn btn-secondary">Actualizar Viaje</button>
</form>


<?php require_once './templates/footer.phtml'; ?>