<form action="agregarDestino" method="GET" class="form-categoria">
    <div>
        <label for="destino">Nombre de destino</label>
        <input class="form-control form-control-sm" name="destino" type="text" placeholder="Nombre destino">
        <label for="imagen">Imagen del destino(URL)</label>
        <input class="form-control form-control-sm" name="img" type="text" placeholder="Url IMG">
    </div>
    <button type="submit" class="btn btn-secondary">Agregar destino</button>
</form>