<?php
require_once './templates/header.phtml';
?>

<div class="login">

    <form method="POST" action="auth" class="mb-3">

        <div>
            <label class="form-label">Usuario</label>
            <input class="form-control" type="text" name="user" placeholder="Ingresar Usuario">
        </div>
        <br>
        <div>
            <label class="form-label">Contraseña</label>
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <br>
        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <div>
    </form>

    <div class="dos">
        <button class="btn btn-primary mb-3" type="submit">acceder</button>
        <a class="btn btn-primary mb-3" href="singup">crear cuenta</a>
    </div>
</div>

<?php require_once './templates/footer.phtml'; ?>